config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  root "static_pages#home"
  get  "/admin",  to: "admin/books#index"
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {registrations: "registrations"}
  resources :books, only: [:index, :show]
  namespace :admin do
    resources :books, except: :show
    resources :categories, except: :show
    resources :users, only: [:index, :destroy]
    resources :requests, except: [:new, :create]
  end
  require "sidekiq/web"
  mount Sidekiq::Web, at: "/sidekiq"
  resources :marks
  resources :favorites, only: [:index, :create, :destroy]
  resources :reviews, except: [:new, :index]
  resources :users, only: :show do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :relationships, only: [:create, :destroy]
  resources :requests, except: [:index]
  resources :comments, except: [:new, :show, :index]
  resources :likes, only: [:create, :destroy]
  resources :search, only: :index
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :reviews, dependent: :destroy
  has_one :request, dependent: :destroy
  has_many :marks

  validates :title, presence: true,
    length: {maximum: Settings.max_lenght_title}
  validates :publish_date, presence: true
  validates :author, presence: true
  validates :number_of_pages, presence: true
  validates :introduce, presence: true,
    length: {maximum: Settings.max_lenght_book_introduce}

  accepts_nested_attributes_for :request, allow_destroy: true

  default_scope {where deleted: false, bought: true}
  scope :delete_commentators_of_review, ->review_id do
    where(review_id: review_id).update_all(deleted: true)
  end

  mount_uploader :cover, PictureUploader

  delegate :name, to: :category, allow_nil: true

  def delete
    self.update_attributes deleted: true
  end

  scope :search, ->keyword {where "title LIKE ?", "%#{keyword}%" if keyword.present?}
  scope :of_category, ->category_id {where category_id: category_id if category_id.present?}
  scope :read, ->{joins(:marks).where "marks.read = ?", true}
  scope :reading, ->{joins(:marks).where "marks.read = ?", false}
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  layout "layouts/admin_layout"
  before_action :load_book, only: [:edit, :update, :destroy]
  before_action :load_category, except: [:update, :destroy]
  before_action :new_book, only: [:index, :new]
  authorize_resource :book

  def index
    @books = Book.search(params[:key]).of_category(params[:category_id]).order(:title)
      .includes(:category).page params[:page]
  end

  def new
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:info] = t :created, objectClass: :book, name: @book.title
      redirect_to admin_books_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update_attributes book_params
      flash[:success] = t :updated, objectClass: :book, name: @book.title
      redirect_to admin_books_path
    else
      render :edit
    end
  end

  def destroy
    unless @book.delete
      flash[:warning] = t :failed, name: @book.title
      redirect_to admin_books_path
    end
  end

  private
  def book_params
    params.require(:book).permit :title, :publish_date, :introduce, :author,
      :number_of_pages, :cover
  end

  def load_book
    @book = Book.find_by id: params[:id]
    unless @book
      flash[:danger] = t :not_fould, objectClass: Book.name
      redirect_to admin_books_path
    end
  end

  def load_category
    @categories = Category.all
  end

  def new_book
    @book = Book.new
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.search(params[:key]).of_category(params[:category_id])
      .page(params[:page]).per Settings.book.per_page_book
    @categories = Category.all
    if user_signed_in?
      @reading_books = current_user.books.reading
      @read_books = current_user.books.read
    end
  end

  def show
    @book = if current_user && current_user.admin
        Book
      else
        Book.unscoped
      end.find_by id: params[:id]
    if @book
      @reviews = @book.reviews.page(params[:page])
        .per Settings.book.per_page_review
      if user_signed_in?
        @review = Review.find_or_initialize_by book_id: @book.id,
          user_id: current_user.id
        @favorite = Favorite.find_by book_id: @book.id, user_id: current_user.id
      end
    else
      flash[:danger] = t :not_fould, objectClass: Book.name
      redirect_to root_url
    end
  end
end

app/views/admin/books/_book.html.erb
<tr id="tr_book_id_<%= book.id %>">
  <td><%= book.id %></td>
  <td>
    <%= book.title %>
  </td>
  <td><%= book.name %></td>
  <td><%= book.publish_date %></td>
  <td><%= book.author %></td>
  <td><%= book.number_of_pages %></td>
  <td>
    <%= link_to edit_admin_book_path(book), class: "btn btn-warning" do %>
      <i class="glyphicon glyphicon-edit"></i>
      <%= t ".edit" %>
    <% end %>
  </td>
  <td>
    <%= button_tag t(:delete),class: "btn btn-danger",
      onclick: "deleteBook(#{book.id}, '#{t(:confirm_delete,
      type: t(".book"), name: book.id)}')" %>
  </td>
</tr>

app/views/admin/books/_form.html.erb
<%= form_for @book, url: yield(:form_url),
  method: yield(:form_method), html: { multipart: true } do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :number_of_pages %>
    <%= f.number_field :number_of_pages, min: 1, step: 1,
      class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.select :category_id,
      options_from_collection_for_select(@categories, :id, :name,
        params[:category_id]), {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :introduce %>
    <%= f.text_area :introduce, class: "form-control ckeditor" %>
  </div>
  <div class="form-group">
    <%= f.label :publish_date %>
    <%= f.date_field :publish_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <span class="picture">
      <%= f.file_field :cover %>
    </span>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/books/edit.html.erb
<% provide :title, t(".title", name: @book.title) %>
<% provide :button_text, t(".button_text") %>
<% provide :form_method, :patch %>
<% provide :form_url, admin_book_path(@book) %>
<div class="col-xs-12">
  <h1><%= t ".title_h1" %></h1>
  <%= render "form" %>
</div>

app/views/admin/books/index.html.erb
<% provide :title, t(".title_page")%>
<% provide :button_text, t(".add_new_book")%>
<% provide :form_method, :post %>
<% provide :form_url, admin_books_path(@book) %>
<div class="row">
  <h1><%= t ".books" %></h1>
</div>
<hr>
<div class="row">
  <div class="col-md-2 col-xs-12">
    <%= link_to "#",
      data: {toggle: "modal", target: "#new-book-modal"},
      class: "btn btn-primary" do %>
      <i class="glyphicon glyphicon-pencil" ></i>
      <%= t ".add_new_book" %>
    <% end %>
  </div>
  <div class="col-md-10 col-xs-12">
    <div class="row">
      <%= form_tag admin_books_path, method: :get, id: "search_books_form" do %>
        <div class="form-inline pull-right">
          <div class="form-group">
            <%= label_tag :Category %>
            <%= select_tag :category_id,
              options_from_collection_for_select(@categories,
              "id", "name", params[:category_id]), include_blank: t("all"),
              class: "form-control", onchange: "submit_books_search_form();",
              id: "select_category_id" %>
          </div>
          <div class="form-group">
            <div class="input-group">
              <%= text_field_tag :key, params[:key],
                class: "form-control",placeholder: t(:search_placeholder), id:"search_books" %>
              <div class="input-group-btn">
                <%= submit_tag t(:search), class: "btn btn-info" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="modal fade" id="new-book-modal" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          &times;
        </button>
        <h3 class="modal-title glyphicon glyphicon-edit">
          <%= t ".book" %>
        </h3>
      </div>
      <div class="modal-body">
        <%= render "form" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default"
          data-dismiss="modal">
          <%= t ".close" %>
        </button>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="row">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th><%= t :id %></th>
        <th><%= t ".title" %></th>
        <th><%= t ".category" %></th>
        <th><%= t ".publish_date" %></th>
        <th><%= t ".author" %></th>
        <th><%= t ".number_of_pages" %></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <div class="alert alert-danger hide" id="connect_failed">
      <label >
        <%= t :failed_connection %>
      </label>
    </div>
    <tbody id="books">
      <%= render @books if @books.any? %>
    </tbody>
  </table>
  <div class="row text-center" id="paginate">
    <%= paginate @books, theme: "twitter-bootstrap-3" if @books.any? %>
  </div>
</div>

app/views/admin/books/index.js.erb
$('#books').html('<%= j render @books %>');
$('#paginate').html('<%= j paginate @books, theme: "twitter-bootstrap-3" %>');

app/views/admin/books/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".title") %>
<% provide :form_method, :post %>
<% provide :form_url, admin_books_path(@book) %>
<div class="col-xs-12">
  <h1><%= t ".title" %></h1>
  <%= render "form" %>
</div>