config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  root "static_pages#home"
  get  "/admin",  to: "admin/books#index"
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {registrations: "registrations"}
  resources :books, only: [:index, :show]
  namespace :admin do
    resources :books, except: :show
    resources :categories, except: :show
    resources :users, only: [:index, :destroy]
    resources :requests, except: [:new, :create]
  end
  require "sidekiq/web"
  mount Sidekiq::Web, at: "/sidekiq"
  resources :marks
  resources :favorites, only: [:index, :create, :destroy]
  resources :reviews, except: [:new, :index]
  resources :users, only: :show do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :relationships, only: [:create, :destroy]
  resources :requests, except: [:index]
  resources :comments, except: [:new, :show, :index]
  resources :likes, only: [:create, :destroy]
  resources :search, only: :index
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :description, presence: true,
    length: {maximum: Settings.max_lenght_request_description}

  scope :have_processed, -> do
    joins_book.where("processed = ? OR books.bought = ?", true, true)
  end
  scope :of_user, ->keyword do
    joins(:user).where("users.name LIKE ?", "%#{keyword}%")
  end
  scope :of_category, ->category_id do
    joins_book
    .where("books.category_id = ? ", category_id) if category_id.present?
  end
  scope :search_titile, ->keyword do
    joins_book.where("books.title LIKE ?", "%#{keyword}%")
  end
  scope :joins_book, ->do
    joins("LEFT JOIN books ON book_id = books.id")
  end

  delegate :title, to: :book, allow_nil: true
  delegate :name, to: :user, allow_nil: true

  default_scope {where deleted: false}

  after_update :send_mail_approved_request

  def delete
    self.update_attributes deleted: true
  end

  def book
    Book.unscoped{super}
  end

  private
  def send_mail_approved_request
    if deleted
      MailerWorker.perform_async MailerWorker::MAIL_DELETE_REQUEST, id, Request.name
    end
  end
end

app/controllers/admin/requests_controller.rb
class Admin::RequestsController < ApplicationController
  layout "layouts/admin_layout"
  authorize_resource
  before_action :load_request, only: [:update, :destroy]

  def index
    @categories = Category.all
    @requests = Request.includes(:user)
      .of_user(params[:user_name]).search_titile(params[:book_title])
      .of_category(params[:category_id]).page params[:page]
  end

  def update
    @messages = Hash.new
    if params[:processed].present?
      approve_request
    end
    if params[:bought].present?
      bought
    end
  end

  def destroy
    if @request.delete
      flash[:warning] = t :delete_success, name: :request
    else
      flash[:danger] = t :delete_failed, name: :request
    end
    redirect_to admin_requests_path
  end

  private
  def load_request
    @request = Request.find_by id: params[:id]
    unless @request
      flash[:danger] = t :not_fould, objectClass: Request.name
      redirect_to admin_requests_path and return
    end
  end

  def approve_request
    @request.processed = params[:processed]
    if @request.save
      @messages[:warning] = is(params[:processed]) ? t(:approve) : t(:unapprove)
    else
      @messages[:danger] = t :faild
    end
  end

  def bought
    @book = @request.book
    @book.bought = params[:bought]
    if @book.save
      @messages[:info] = is(params[:bought]) ? t(:bought) : t(:not_bought)
    else
      @messages[:danger] = t :faild
    end
  end

  def is str
    str == Settings.true
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :load_request, except: [:index, :new, :create]
  before_action :processed?, only: [:edit, :update]
  before_action :load_category, except: [:update, :destroy]
  authorize_resource

  def new
    @book = Book.new
    @book.request = Request.new
  end

  def create
    @book = Book.new book_params
    @book.bought = false
    @book.request.user_id = current_user.id
    if @book.save
      flash[:info] = t :created, objectClass: :request, name: @book.title
      redirect_to @book.request
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @request.book.update_attributes book_params
      flash[:success] = t :updated, objectClass: :request, name: @book.title
      redirect_to @request
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @book.destroy unless @book.bought
    if @request.destroy
      flash[:warning] = t :delete_success, name: :request
    else
      flash[:danger] = t :delete_failed, name: :request
    end
    redirect_to root_url
  end

  private
  def book_params
    params.require(:book).permit :title, :publish_date, :introduce, :author,
      :number_of_pages, :cover, :category_id,
      request_attributes: [:id, :description]
  end

  def load_request
    @request = Request.find_by id: params[:id]
    unless @request
      flash[:danger] = t :not_fould, objectClass: Request.name
      redirect_to root_path and return
    end
    @book = @request.book
    unless @book
      flash[:danger] = t :lost_request_book
      redirect_to root_path and return
    end
  end

  def processed?
    if @request.book.bought || @request.processed
      flash[:warning] = t :request_has_processed
      redirect_to root_path and return
    end
  end

  def load_category
    @categories = Category.all
  end
end

app/views/requests/_form.html.erb
<%= form_for @book, url: yield(:form_url),
  method: yield(:form_method), html: {multipart: true} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :number_of_pages %>
    <%= f.number_field :number_of_pages, min: 1, step: 1,
      class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.select :category_id,
      options_from_collection_for_select(@categories, :id, :name,
        params[:category_id]), {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :introduce %>
    <%= f.text_area :introduce, class: "form-control ckeditor" %>
  </div>
  <div class="form-group">
    <%= f.label :publish_date %>
    <%= f.date_field :publish_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <span class="picture">
      <%= f.file_field :cover %>
    </span>
  </div>
  <div class="form-group">
    <%= f.fields_for :request do |request| %>
      <%= request.label :description %>
      <%= request.text_area :description, class: "form-control ckeditor" %>
    <% end %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/requests/_request_well.html.erb
<li class="well">
  <%= link_to image_tag(request.book.cover, alt: request.title,
    size: Settings.user.size_of_book_cover, class: "book-cover"), request %>
  <%= show_book_title request.book %> - <%= request.book.author %>
</li>

app/views/requests/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".button_text") %>
<% provide :form_method, :patch %>
<% provide :form_url, request_path(@request) %>
<div class="col-xs-12">
  <h1><%= t ".title_h1" %></h1>
  <%= render "form" %>
</div>

app/views/requests/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".title") %>
<% provide :form_method, :post %>
<% provide :form_url, requests_path(@book) %>
<div class="col-xs-12">
  <h1><%= t ".title" %></h1>
  <%= render "form" %>
</div>

app/views/requests/show.html.erb
<% provide :title, t(".title", book: @book.title) %>
<div class="row">
  <div class="container book-background">
    <%= render "books/book_info" %>
  </div>
</div>
<div class="row">
  <div class="panel panel-info col-md-12 col-xs-12">
    <div class="panel-heading ">
      <%= t ".introduce" %>
    </div>
    <div class="panel-body">
      <%= @book.introduce.html_safe %>
    </div>
  </div>
</div>
<div class="row">
  <div class="panel panel-info col-md-12 col-xs-12">
    <div class="panel-heading ">
      <h2><%= t ".description" %></h2>
    </div>
    <div class="panel-body">
      <%= @request.description.html_safe %>
    </div>
  </div>
</div>
<div class="row pull-right">
  <td>
    <%= link_to edit_request_path(@request), class: "btn btn-warning" do %>
      <i class="glyphicon glyphicon-edit"></i>
      <%= t ".edit" %>
    <% end %>
  </td>
  <td>
    <%= link_to request_path(@request), method: :delete,
      class: "btn btn-danger" do %>
      <i class="glyphicon glyphicon-remove"></i>
      <%= t ".delete" %>
    <% end %>
  </td>
</div>