config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  root "static_pages#home"
  get  "/admin",  to: "admin/books#index"
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {registrations: "registrations"}
  resources :books, only: [:index, :show]
  namespace :admin do
    resources :books, except: :show
    resources :categories, except: :show
    resources :users, only: [:index, :destroy]
    resources :requests, except: [:new, :create]
  end
  require "sidekiq/web"
  mount Sidekiq::Web, at: "/sidekiq"
  resources :marks
  resources :favorites, only: [:index, :create, :destroy]
  resources :reviews, except: [:new, :index]
  resources :users, only: :show do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :relationships, only: [:create, :destroy]
  resources :requests, except: [:index]
  resources :comments, except: [:new, :show, :index]
  resources :likes, only: [:create, :destroy]
  resources :search, only: :index
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :find_user

  def index
    @users = @user.followers.search(params[:key]).page(params[:page])
      .per Settings.user_per_page
  end
end

app/views/followers/index.html.erb
<% provide :title, t(".title",name: @user.name) %>
<% provide :header_title, t(".title",name: @user.name) %>
<% provide :search_id, "search_follows_box" %>
<% provide :path_search, user_followers_path(@user) %>
<%= render "users/users" %>

app/views/followers/index.js.erb
$('#result_search').html('<%= j render @users %>');
$('#paginate').html('<%= j paginate @users %>');