config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  root "static_pages#home"
  get  "/admin",  to: "admin/books#index"
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {registrations: "registrations"}
  resources :books, only: [:index, :show]
  namespace :admin do
    resources :books, except: :show
    resources :categories, except: :show
    resources :users, only: [:index, :destroy]
    resources :requests, except: [:new, :create]
  end
  require "sidekiq/web"
  mount Sidekiq::Web, at: "/sidekiq"
  resources :marks
  resources :favorites, only: [:index, :create, :destroy]
  resources :reviews, except: [:new, :index]
  resources :users, only: :show do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :relationships, only: [:create, :destroy]
  resources :requests, except: [:index]
  resources :comments, except: [:new, :show, :index]
  resources :likes, only: [:create, :destroy]
  resources :search, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :protected_token
  has_many :activities, dependent: :destroy
  has_many :active_relationships,
    class_name: Relationship.name,
    foreign_key: :follower_id,
    dependent: :destroy
  has_many :following, through: :active_relationships,
    source: :followed
  has_many :passive_relationships,
    class_name: Relationship.name,
    foreign_key: :followed_id,
    dependent: :destroy
  has_many :followers, through: :passive_relationships,
    source: :follower
  has_many :reviews
  has_many :commentators, dependent: :destroy
  has_many :comments, through: :commentators
  has_many :marks, dependent: :destroy
  has_many :books, through: :marks
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, class_name: Book.name, through: :favorites, source: :book
  has_many :likes
  has_many :requests

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: {maximum: Settings.max_lenght_name}
  validates :email, presence: true, length: {maximum: Settings.max_lenght_email},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}

  validates :password, presence: true,
    length: {minimum: Settings.min_lenght_password,
    maximum: Settings.max_length_password}, allow_nil: true

  mount_uploader :avatar, PictureUploader

  scope :search, ->keyword {where "name LIKE ?", "%#{keyword}%"}
  scope :reviewers_of_book, ->book_id do
    joins(:reviews).where("reviews.book_id = ?", book_id).group("users.id")
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "layouts/admin_layout"
  load_and_authorize_resource
  before_action :load_user, only: :destroy

  def index
    @users = User.search(params[:key]).page(params[:page])
      .per Settings.per_page_user
  end

  def destroy
    unless @user.destroy
      flash[:warning] = t :failed, name: @user.name
      redirect_to users
    end
  end

  private
  def user_params
    params.require(:user).permit :name,
      :birthday, :email, :sex, :address,
      :password, :password_confirmation, :avatar
  end

  def load_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t :user_not_found
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t :user_not_found
      redirect_to root_url and return
    end
    @activities = Activity.users_activities(@user.id).page(params[:page_activities])
      .per Settings.user.activities_per_page
    @reading_books = @user.books.reading.page(params[:page_reading_books])
      .per Settings.user.activities_per_page
    @read_books = @user.books.read.page(params[:page_read_books])
      .per Settings.user.activities_per_page
    @favorites = @user.favorite_books.page(params[:page_favorites])
      .per Settings.user.activities_per_page
    @requests = @user.requests.page(params[:page_requests])
      .per Settings.user.activities_per_page
    if user_signed_in?
      @relationship = current_user.active_relationships
        .find_or_initialize_by followed_id: @user.id
    end
  end
end

app/views/admin/users/_user.html.erb
<tr id="user_content_id_<%= user.id %>">
  <td><%= user.id %></td>
  <td><%= user.name %></td>
  <td><%= user.sex %></td>
  <td><%= user.birthday %></td>
  <td>
    <% if user_signed_in? && current_user != user && current_user.admin?%>
      <%= button_tag t(:delete),class: "btn btn-danger",
        onclick: "deleteUser('#{user.id}', '#{t(:confirm_delete,
        type: t(".user"), name: user.name)}')" %>
    <% end %>
  </td>
</tr>

app/views/admin/users/index.html.erb
<% provide :title, t(".title") %>
<% provide :header_title, t(".title") %>
<div class="row">
  <%= form_tag admin_users_path, method: :get, id: "search_users" do %>
    <div class="row panel">
      <div class="input-group pull-right">
        <%= text_field_tag :key, params[:key], id: "search_user_box",
          class: "form-control", placeholder: t(:search_placeholder ) %>
        <div class="input-group-btn">
          <%= submit_tag t(:search), class: "btn btn-info" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="row">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th><%= t :id %></th>
        <th><%= t ".name" %></th>
        <th><%= t ".sex" %></th>
        <th><%= t ".birthday" %></th>
        <th></th>
      </tr>
    </thead>
    <div class="alert alert-danger hide" id="connect_failed">
      <label >
        <%= t :failed_connection %>
      </label>
    </div>
    <tbody id="result_search">
      <div class="row">
        <%= render @users if @users.any? %>
      </div>
    </tbody>
  </table>
  <div class="row text-center" id="paginate">
    <%= paginate @users, theme: "twitter-bootstrap-3" if @users.any? %>
  </div>
</div>

app/views/admin/users/index.js.erb
$('#result_search').html('<%= j render @users %>');
$('#will_paginate').html('<%= j paginate @users %>');